# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GridGeneratorDockWidget
                                 A QGIS plugin
 Creates UTM and geopgraphic symbology and labels for given bounding feature.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-21
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Joao Felipe Aguiar Guimaraes
        email                : joao.felipe@eb.mil.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic 
from qgis.PyQt.QtGui import QColor, QFont
from qgis.PyQt.QtCore import pyqtSignal
from qgis.gui import QgsMapLayerComboBox, QgsFieldComboBox, QgsSpinBox, QgsDoubleSpinBox, QgsColorButton
from qgis.core import QgsVectorLayer, QgsMapLayerProxyModel
from .gui.gridAndLabelCreator import *



FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gridGenerator_dockwidget_base.ui'))


class GridGeneratorDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(GridGeneratorDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.gridAndLabelCreator = GridAndLabelCreator()
        self.setupUi(self)
        self.mapLayerSelection.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        self.mapLayerSelection.layerChanged.connect(self.idSelection.setLayer)

        self.okButton.pressed.connect(self.send_inputs)
        self.resetButton.pressed.connect(self.send_reset)


    def send_inputs(self):

        if (not self.mapLayerSelection.currentLayer()) and (self.idSelection.currentField()) and (self.idValue.value()) and (self.utmSpacing.value()) and (self.crossesX.value()) and (self.crossesY.value()) and (self.mapScale.value()) and (self.gridColor.color()) and (self.labelFontSize.value()) and (self.fontType.currentFont()) and (self.fontTypeLL.currentFont()) and (self.width_geo.value()) and (self.width_utm.value()):
            return

        layer = self.mapLayerSelection.currentLayer()
        id_attr = self.idSelection.currentField()
        id_value = self.idValue.value()
        spacing = self.utmSpacing.value()
        crossX = self.crossesX.value()
        crossY = self.crossesY.value()
        scale = self.mapScale.value()
        color = self.gridColor.color()
        fontSize = self.labelFontSize.value()
        font = self.fontType.currentFont()
        fontLL = self.fontTypeLL.currentFont()
        llcolor = self.llColor.color()
        linwidth_geo = self.width_geo.value()
        linwidth_utm = self.width_utm.value()
        self.gridAndLabelCreator.geo_test(layer, id_attr, id_value, spacing, crossX, crossY, scale, color, fontSize, font, fontLL, llcolor, linwidth_geo, linwidth_utm)


    def send_reset(self):
        layer = self.mapLayerSelection.currentLayer()
        self.gridAndLabelCreator.reset(layer)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
